btcsuite/btcwallet

- btcwallet.go
- chain/chain.go
- config.go
- rpcserver.go
Refs #157 
Added two config params:
* `DisableServerTLS` `--noservertls` This disables TLS for the wallet RPC server and is localhost only
* `DisableClientTLS`  `--noclientts` This disables TLS when connecting to RPC server and is also localhost only. There's a risk of leaking sensitive data when switching between localhost and remote btcd servers so I think it's better to prevent that and have the same non-localhost checks for this too.
> Add --notls support to wallet rpc server

- waddrmgr/manager.go
The slice of keys which must have their private extended keys derived
on unlock was never being removed from and all of these keys were
being rederived unnecessarily on every unlock.  Fix this by re-slicing
the deriveOnUnlock slice to remove the just derived key if the
derivation was successful.
> waddrmgr: Avoid unnecessarily rederiving keys on unlock.

- waddrmgr/manager.go
This is performed by saving the SHA512(salt+passphrase) of the
waddrmgr.Manager private passphrase each time the manager is unlocked.
If another call to Unlock is performed before the next Lock, the hash
is applied to the new input.  If it matches, we know the passphrase is
(likely) equal, so return early and continue using the crypto keys
already in memory.  If it does not match, we know for certain the
passphrase is incorrect and the manager is locked.
> Optimize unlocks for already unlocked addrmgrs.

- waddrmgr/doc.go
This pull request updates the documentation which discusses creating and opening the manager to properly mention the wallet database namespace as well as another typo.
> waddrmgr: Update documentation for walletdb.

- createtx.go
- rpcserver.go
By using txscript.StandardVerifyFlags when creating and validating
transactions, we can ensure the transactions successfully created
will be accepted by btcd.
> Use txscript.StandardVerifyFlags

- rpcserver.go
- wallet.go
Wallet should handle these so that wallet clients don't end up
creating requests to btcd about the latest processed block, which is
not the same as wallet's most recently processed block.
By providing wallet clients with this info, we avoid a race where the
client thinks wallet has processed N blocks, but in fact is still
synced to N-1 (and perhaps currently processing transactions from
block N).  This can cause unexpected results for many of the
bitcoind-compatible RPC APIs due to their reliance on number of
confirmations, rather than using absolute block heights.
> Implement several btcd RPCs in wallet as well.

- chain/chain.go
- chainntfns.go
- rescan.go
- rpcserver.go
- wallet.go
Otherwise, if the websocket connection to btcd is lost and
reestablished, there is no sync to the current best block, and btcd
will not notify wallet of new relevant transactions.
> Rescan after btcd reconnect.

- waddrmgr/db.go
- waddrmgr/error.go
- waddrmgr/error_test.go
- waddrmgr/internal_test.go
- waddrmgr/manager.go
- waddrmgr/manager_test.go
This pull request makes the creation and updating of the address manager more explicit so it's easier to upgrade in the future.
In particular, rather than treating the initial creation as an upgrade by relying on creating the initial buckets on the fly on each load, the code now explicitly provides distinct create and upgrade paths that are invoked from the `Create` and `Open` functions, respectively.
It also adds some commented out sample code to illustrate how upgrades should be done and a check to ensure bumping the version number without writing upgrade code results in a new error, `ErrUpgrade`, being returned.
Finally, a test has been added for the new functionality.
> waddrmgr: Make create/update logic more explicit.

- internal/zero/benchmark_test.go
- internal/zero/zero.go
- internal/zero/zero_test.go
- snacl/snacl.go
- votingpool/pool.go
- waddrmgr/address.go
- waddrmgr/manager.go
Removes an XXX from the votingpool package.
I didn't touch the zero functions in the keystore package as it is being deprecated and would like to avoid any unnecessary merge conflicts from moving that to the legacy directory.
Zeroing is also performed in hdkeychain, so do we want this here, or somewhere else in our libraries so hdkeychain can also take advantage?  Alternatively, when the btcutil repo is split, we can move hdkeychain to btcwallet, and then update it to use this package.
Benchmarks from a xeon e3 (Bytes is the byte slice zeroing func provided by this package, Bytea* are the fixed-size funcs):
```
BenchmarkXor32  30000000                52.1 ns/op
BenchmarkXor64  20000000                91.5 ns/op
BenchmarkRange32        50000000                31.8 ns/op
BenchmarkRange64 …
```
> Consolidate and optimize zero functions.

- chainntfns.go
- waddrmgr/address.go
- waddrmgr/db.go
- waddrmgr/manager.go
- waddrmgr/manager_test.go
- wallet.go
Added a database flag on Address to mark used addresses and prevent address re-use.
Refs #196
> Mark addresses used 

- chain/chain.go
btcrpcclient commit 9ca93b30ad11ec34348d2d788c58019571bf9524 switched
the client to btcjson v2 and broke the wallet build.  This change is
the minimum amount of work to make wallet work again.
The rpc server still uses btcjson v1, so there will be 2 versions of
btcjson linked in the resulting binary.  This is not optimal but not
compiling is worse.
> Use btcjson v2 types with the updated btcrpcclient.

- waddrmgr/address.go
- waddrmgr/db.go
- waddrmgr/manager.go
- waddrmgr/manager_test.go
- wallet/wallet.go
Fixed `Last(In/Ex)ternalAddress` to make sure `CurrentAddress` returns a new address when the first and subsequent addresses are flagged as used.
> CurrentAddress - mark first address used and return new address

- waddrmgr/common_test.go
- waddrmgr/manager_test.go
Added test coverage for account related manager funcs.
> Improve account related test coverage

- votingpool/error.go
- votingpool/error_test.go
- votingpool/withdrawal.go
- votingpool/withdrawal_wb_test.go
This is not yet used but will be needed for the implementation of the updatewithdrawal API, which will be coming soon.
~~Depends on #234~~
> votingpool: API to store withdrawal txs in the txstore

- waddrmgr/db.go
If the account number to name index mapped the default account name to
an alias, the upgrade would not succeed and the upgrade would be
aborted (and rolled back).
This became a problem for upgrading old (pre-v3) wallets since the v3
upgrade did not rename the previous "" account to "default", but
instead just created an alias.
Fix tested by @dajohi, who ran into this issue with a wallet upgrade
from an older keystore version.
> Fix waddrmgr version 4 upgrade path.

- wallet/wallet.go
This matches Bitcoin Core Wallet.
Fixes #272.
> Use negative fees with listtransaction result types.

- wallet/wallet.go
> Use 0 instead of -1 for zero-conf listtransactions results.

- wallet/chainntfns.go
If a long reorganize occurs farther back than the last saved recent
block hash (currently max 20 are saved) a full rescan is triggered
since there is no guarantee the previous blocks weren't also removed
in the reorg.  In this case, the address manager was set unsynced, but
transaction history was not rolled back as well.  This commit corrects
this by unconfirming all transactions but those in the genesis block.
> Rollback transactions past the last saved recent block.

- votingpool/common_test.go
- votingpool/factory_test.go
- votingpool/withdrawal.go
- votingpool/withdrawal_wb_test.go
Doing that may cause erratic test failures when we run them in parallel, so
move the functions the tests need to mock as struct fields that are not
shared across tests.
> Stop mocking global func() variables in votingpool tests

- rpcserver.go
- waddrmgr/db.go
- waddrmgr/error.go
- waddrmgr/manager.go
- waddrmgr/manager_test.go
- wallet/wallet.go
refs #215 
WIP: Trying out the approach by replacing `AllAccounts` with a `each` style func first.
> waddrmgr: optimize using each style functions

- rpcserver.go
- wallet/wallet.go
sync.Locker cannot be safely used to switch a sync.Mutex to a noop
locker since other goroutines that attempt to lock the mutex will race
on the changing interface.  Instead, just statically dispatch
sync.Mutex methods.
> Remove data races from switching lock impls.

- waddrmgr/manager.go
To fix a race detected with -race detector
> Add mutex for delete(m.addrs, ..) in MarkUsed

- wtxmgr/query.go
This reverses the order of index and amount fields to match
DebitRecord and also saves 8 bytes per instance on amd64.
> Reorder wtxmgr.CreditRecord fields.

- waddrmgr/manager.go
In particular, this allows the use of AccountName in the passed
function when iterating over all account numbers.
> Remove unnecessary address manager locks.

- waddrmgr/manager.go
The behaviour of function Address() in waddrmgr has been updated such that
it now displays the correct behaviour as described in the comments. That is,
when a public key address is given as a btcutil.Address, the key is converted
to a public key hash address so that serializing with ScriptAddress() yields
the corresponding public key hash. This allows the address manager to find
the corresponding private key, and fixes the signing of multisignature
transactions.
> Fix retrieval of public key addresses from address manager

- rpcserver.go
AFAICT this function has never worked correctly due to the hash being
signed not matching the hash created by Core.  Core wallet writes
serialized strings to a double-sha256 hashing stream, while we were
using string concatination.  This produced different messages since
the message before hashing did not include compact integers (called
varints in btcsuite code) preceding each string with the string
length.
Tested by creating signed messages from btcwallet and verifying them
with Bitcoin-Qt, as well as creating signatures from Bitcoin-Qt and
verifying them with btcwallet.
> Fix signmessage RPC to match Core.

- chain/chain.go
- log.go
This isn't really a subsystem, rather a dependency, but being able to
turn the logging on from the command line can greatly simplify debugging
of connectivity issues.
> Add logging option for btcrpcclient as subsystem RPCC.

- config.go
- internal/cfgutil/file.go
- internal/cfgutil/normalization.go
- netparams/params.go
- rpcserver.go
- walletsetup.go
This change moves the chain and network parameter definitions, along
with the default client and server ports, to a package for reuse by
other utilities (most notably, tools in the cmd dir).  Along with it,
functions commonly used for config parsing and validation are moved to
an internal package since they will also be useful for distributed
tools.
> Separate out default ports and utility funcs.

- wallet/loader.go
Previously, if a nil seed was passed into loader.CreateNewWallet, a
random seed was never generated. This would cause an error within the
waddrmgr due to the seed being of invalid (0) length.
> Generate a seed when creating a new wallet if none was provided.

- wallet/wallet.go
Use waddrmgr.IsError to avoid logging errors when trying to lock an
already locked wallet.
Fixes #349.
> Always lock waddrmgr for every timeout or explicit request.

- rpc/legacyrpc/methods.go
This prevents the server from returning an error when empty strings
are passed as parameters for transaction comments for the
sendfrom/sendmany/sendtoaddress RPCs.  Non-empty strings will still
cause errors since transaction comments are not saved.
Fixes #356.
> Do not error for empty tx comments.

- rpc/legacyrpc/methods.go
This only sets the name for any kind of "receiving" category
(receive/immature/generate).
Fixes #360.
> Set account name for gettransaction results.

- README.md
While here, remove mention of btcgui and add a disclaimer that total
compatibility with the JSON-RPC server cannot be achieved.
> Update README for gRPC changes.

- config.go
- rpcserver.go
- sample-btcwallet.conf
This option prevents the RPC server TLS key from ever being written to
disk.  This is performed by generating a new certificate pair each
startup and writing (possibly overwriting) the certificate but not the
key.
Closes #359.
> Add option for one time TLS keys.

- config.go
This was initially pointed out by davec in
decred/dcrwallet#18
> If wallet already exists show path.

- rpc/rpcserver/server.go
- wallet/notifications.go
The gRPC server requires this as it must include the properties of
every transaction output, not just those that are controlled by the
wallet.
> Create results for each wallet.TransactionSummary output.

- rpc/legacyrpc/methods.go
This broke when the Unlock API changed to replace the timeout in
seconds with a time.Time channel.
> Make walletpassphrase with timeout=0 never lock the wallet.

- rpc/rpcserver/server.go
The specification states that even when the target output amount
cannot be reached, all available outputs should still be included in
the response and it is up to the caller to check that the target can
be satisified or not.  Follow this behavior by not erroring when the
target was not met.
> Follow specification for FundTransaction RPC.

- rpc/legacyrpc/methods.go
- wallet/createtx.go
- wallet/wallet.go
This prevents races when setting a new relay fee through the legacy
RPC server (settxfee).
Fixes #379.
> Protect the relay fee field with a mutex.

- btcwallet.go
- rpc/rpcserver/server.go
- wallet/loader.go
- walletsetup.go
This corrects and simplifies the shutdown logic for interrupts, the
walletrpc.WalletLoaderService/CloseWallet RPC, and the legacy stop RPC
by both stopping all wallet processes and closing the wallet database.
It appears that this behavior broke as part of the wallet package
refactor, causing occasional nil pointer panics and memory faults when
closing the wallet database with active transactions.
Fixes #282.
Fixes #283.
> Stop wallet and close wallet DB on interrupt.

- README.md
- config.go
- params.go
- sample-btcwallet.conf
Note that this is a breaking change since it removes the mainnet
config option, replacing it with a testnet option.  Old configuration
files that set mainnet=1 will cause the wallet to error during startup
since extraneous flags are treated as errors.
Closes #383.
> Default to mainnet.

- waddrmgr/manager.go
- waddrmgr/manager_test.go
This change only prevents creating new accounts with the empty name or
renaming an existing account to one.  Any accounts in the DB that are
already named the empty string are left untouched (and should be
renamed to something meaningful by the user).
Fixes #369.
> Disallow naming accounts the empty string.

- rpc/legacyrpc/server.go
- wallet/chainntfns.go
- wallet/rescan.go
- wallet/wallet.go
These notifications were added to support real time updates for
btcgui.  As the btcgui project is no longer being developed, there are
no more consumers of this API, and it makes sense to remove them given
their various issues (the largest being that notifiations are sent
unsubscribed to clients that may never be interrested in them).
A new notification server has already been added to the wallet package
to handle notifications in a RPC-server agnostic way.  This server is
the means by which the wallet notifies changes for gRPC clients.  If
per-client registered notifications are to be re-added for the
JSON-RPC server, they should be integrated with the new notification
server rather than using this legacy code.
> Remove legacy JSON-RPC notifications.

- btcwallet.go
This makes btcwallet match btcd's behavior.
Initially pointed out in:
decred/dcrwallet#125
> Print version string at startup.

- votingpool/example_test.go
- votingpool/factory_test.go
- waddrmgr/common_test.go
- waddrmgr/manager.go
- waddrmgr/manager_test.go
- wallet/loader.go
- wallet/wallet.go
- walletdb/interface.go
- walletsetup.go
- wtxmgr/example_test.go
- wtxmgr/tx.go
- wtxmgr/tx_test.go
This changes the wallet.Open function signature to remove the database
namespace parameters.  This is done so that the wallet package itself
is responsible for the location and opening of these namespaces from
the database, rather than requiring the caller to open these ahead of
time.
A new wallet.Create function has also been added.  This function
initializes a new wallet in an empty database, using the same
namespaces as wallet.Open will eventually use.  This relieves the
caller from needing to manage wallet database namespaces explicitly.
Fixes #397.
> Manage wallet db namespaces from wallet package.

- .travis.yml
- chain/chain.go
- goclean.sh
- internal/helpers/helpers.go
- internal/rpchelp/methods.go
- rpc/rpcserver/server.go
- snacl/snacl.go
- waddrmgr/db.go
- waddrmgr/manager.go
- wallet/rescan.go
- wtxmgr/query_test.go
- wtxmgr/tx_test.go
This cleans up some things caught by goclean's various tests in btcwallet and enables it's use with travis.
This catches btcwallet up with the rest of btcsuite in this regard and will help get dcrwallet to the same point.
I have not squashed this yet in case @jrick takes issue with any particular fixes (or things that I made the tests ignore).
> Use goclean like the rest of btcsuite.

- wtxmgr/kahnsort.go
- wtxmgr/unconfirmed.go
This changes the wtxmgr.Store.UnminedTxs method to sort transactions,
using the Kahn topological sort algorithm, before returning
transactions to the caller.  This is possible because transactions
form a sort of Directed Acyclic Graph (DAG) where transactions
reference other transactions to spend their outputs (multiple
referenced outputs from a single transaction spent by the same
transaction count as a single graph edge).
This prevents the possibility of orphan rejection errors when sending
unmined transactions to a full node at startup.  As these transactions
are sent using the sendrawtransaction RPC, which does not permit
orphans, this topological sort is required.
Fixes #156.
> Sort unmined transactions in their dependency order.

- walletdb/bdb/db.go
This fixes a deadlock where failed transactions due to the namespaces'
bucket being missing would cause deadlocks due to bolt's mmap rwmutex
still being read locked (and no way to unlock it, since the underlying
bolt tx was not returned on failure).
> Rollback namespace transactions when bucket is not found.

- wallet/wallet.go
> invalid transaction hashes crashes btcwallet

- .travis.yml
The vet tool moved to the Go tree as of go1.5 so it does not
need to be installed seperately.  With the x/tools repo now gone,
remove the install step for vet since it fails.
> Update TravisCI configs.

- rpc/legacyrpc/rpchelp_test.go
This file was accidentally removed when the gRPC server was introduced
and the legacy JSON-RPC server was moved to the legacyrpc package.
> Resurrect rpchelp_test.go

- btcwallet.go
- config.go
- sample-btcwallet.conf
- walletsetup.go
This removes an inconsistency with the datadir option from btcd, which
only set the directory containing the blockchain data and indexes.
> Rename datadir/-b options to appdata/-A.

- wallet/txauthor/author.go
- wallet/txauthor/author_test.go
Due to the way dust is calculated, if the transaction relay fee is
zero, then a zero output amount is not considered dust.  As the
transaction authoring code used this dust check to determine whether a
change output can be included or not, it could create unnecessary
change outputs which return no value back to the wallet.  Prevent this
by including an explicit check for zero values.
> Do not include zero value change outputs.

- .gitignore
- .travis.yml
- README.md
- appveyor.yml
- glide.lock
- glide.yaml
- goclean.sh
> Convert project to glide.

- rpc/documentation/clientusage.md
While here, also rename OpenSSL to BoringSSL since gRPC Core has
switched to that.
Fixes #429.
> Set gRPC cipher suites sooner in node.js example.

- config.go
This fixes home directory expansion on Windows and OS X.  Previously
on these platforms, a leading ~ would expand to %LOCALAPPDATA% on
Windows or ~/Library/Application Support/ on OS X.
While here, add support for ~otheruser expansion to expand to
otheruser's home directory.
> Lookup actual home directory when expanding ~.

- config.go
This modifies the default configuration file to be relative to the
application data directory (configuratble with --appdata).  If there
is no configuration file in this directory, then no additional
configuration options are applied (it does not fallback to
~/.btcwallet/btcwallet.conf).
Fixes #421.
> Make default config relative to appdata directory.

- rpc/documentation/api.md
- rpc/rpcserver/server.go
- wallet/notifications.go
Previously, this would always check a transaction output index against
the 0th credit's index.
> Fix credit slice indexing for transaction notifications.

- config.go
When 29f31725ee57fcf4a1118b420f8c115c2742da0a deprecated the datadir
option, replacing it with --appdata/-A, the short --datadir option was
unintentinally changed from -b to -D.  It was previously changed to -b
in fda2e14b99bba7e8ff4cf0f7434e1f5e8b130205 for consistency with
btcd's --datadir short option.
This change reverts the unintentional switch back to -D.
> Use -b for deprecated --datadir short option.

- rpc/legacyrpc/methods.go
- rpc/legacyrpc/server.go
This unexports every RPC handler function, as well as the
Server.PostClientRPC method which was only called by this package.
Fixes #435.
> Unexport private methods from legacyrpc package.

- signal.go
- signalsigterm.go
When an OS reboots or shuts down, it sends all processes SIGTERM before
sending SIGKILL.  This allows btcwallet to do a proper shutdown which
most importantly closes the databases.
> btcwallet: handle signal SIGTERM

- README.md
The description had previously said that non-vendored packages were
not installed to $GOPATH/bin, but this is incorrect.  Remove this part
of the description so it includes all packages.
> Fix description for recommended install instructions.

- .travis.yml
Previously, the GO15VENDOREXPERIMENT environment variable was unset,
leaving travis to only use the vendored packages during builds for Go
1.6 which enabled the experiment by default.  Export the variable so
it also correctly tests under Go 1.5.
> Enable vendor experiment for Go 1.5 on Travis-CI.

- .travis.yml
- README.md
This will build all (non-vendored) packages recursively, even if they
are not used in any of the binaries (e.g. votingpool).  Additionally,
since a subshell is no longer used, the example commands can be run in
a Windows command prompt.  I don't encourage the use cmd.exe over
alternatives such as PowerShell, but there's no reason this command
could not be run there.
> Don't use go install $(glide novendor) in examples.

- cmd/dropwtxmgr/main.go
- cmd/sweepaccount/main.go
- config.go
- glide.lock
- glide.yaml
In https://github.com/btcsuite/btcwallet/pull/419#issuecomment-212482492
I mentioned that btcwallet should wait until btcd also switches back
to upstream package paths so that duplicate packages are not included
in and bloat the btcwallet binary.  Even while btcd has not yet
switched to the upstream flags package, this change can still be made
now since it is only used by btcd's main package, which is not
included in btcwallet.
> Switch from forked to upstream flags package.

- btcwallet.go
- config.go
- internal/cfgutil/explicitflags.go
- rpcserver.go
- walletsetup.go
This prevents treating a flag that was explicitly set to the default
as unchanged, since the explicit set is recorded in the new
*cfgutil.ExplicitString flag type.
> Handle flags explicitly set to defaults.

- chain/chain.go
- cmd/sweepaccount/main.go
- glide.lock
- internal/legacy/keystore/keystore.go
- internal/legacy/keystore/keystore_test.go
- rpc/legacyrpc/methods.go
- rpc/rpcserver/server.go
- votingpool/factory_test.go
- votingpool/input_selection.go
- votingpool/input_selection_wb_test.go
- votingpool/withdrawal.go
- votingpool/withdrawal_wb_test.go
- waddrmgr/db.go
- waddrmgr/manager.go
- waddrmgr/manager_test.go
- waddrmgr/sync.go
- wallet/notifications.go
- wallet/wallet.go
- wtxmgr/db.go
- wtxmgr/example_test.go
- wtxmgr/kahnsort.go
- wtxmgr/query.go
- wtxmgr/query_test.go
- wtxmgr/tx.go
- wtxmgr/tx_test.go
- wtxmgr/unconfirmed.go
**This PR requires btcsuite/btcd#729 and btcsuite/btcutil#78.**
This updates all code to make use of the new `chainhash` package since the old `wire.ShaHash` type and related functions have been removed in favor of the abstracted package.
Also, while here, rename all variables that included `sha` in their name to include `hash` instead.
Finally, update `glide.lock` to use the required version of `btcd`, `btcutil`, and `btcrpcclient`.
> Update for recent chainhash-related API changes.

- glide.lock
- rpc/legacyrpc/methods.go
- rpc/rpcserver/server.go
- votingpool/example_test.go
- votingpool/factory_test.go
- wallet/createtx.go
- wallet/wallet.go
- wtxmgr/example_test.go
- wtxmgr/tx.go
- wtxmgr/tx_test.go
**This pull request requires btcsuite/btcd#732** 
Since the coinbase maturity is now allowed to be defined per chain and the old `blockchain.CoinbaseMaturity` constant has been removed, this updates the code accordingly.
> Update for recent chaincfg API changes.

- wallet/txauthor/author.go
The word 'transaction' was duplicated.
> Fix typo in comment on AddAllInputScripts. 

- glide.lock
- rpc/legacyrpc/methods.go
- votingpool/db.go
- votingpool/withdrawal.go
- wtxmgr/tx_test.go
**Requires PRs btcsuite/btcutil#82 and btcsuite/btcd#817**
Also, bump glide.lock to ensure the appropriate deps are pulled in.
**NOTE: I modified `glide.yaml` and `glide.lock` temporarily until the upstream deps are in so this PR builds in the mean time.  Those will need to be reverted before this is merged**
> Update for wire.NewMsgTx API change.

- goclean.sh
This just clutters the logs and makes it more difficult to determine
what the actual failing test was. For tests that do fail, all logs
from the test are already outputted.
> Remove -v from go test on travis.

- wallet/wallet.go
Previously, this would not increment the spendable balance for matured
coinbase outputs and would only increment the immature balance if the
output was still immature.
> Fix reported spendable balances from coinbase outputs.

- chain/bitcoind.go
- chain/block_filterer.go
- chain/block_filterer_test.go
- chain/interface.go
- chain/neutrino.go
- chain/rpc.go
- glide.lock
- glide.yaml
- wallet/recovery.go
- wallet/rescan.go
- wallet/wallet.go
In this PR, we update the backends, and also chain recovery logic to be aware of the new neutrino API as a result of the modifications to BIP 158. The major change is that we must now carry along the previous output script along with the outpoint everywhere as we'll now match on the prev output script, but then actually dispatch notifications based on the outpoint.
Replaces #518
> multi: update neutrino gcs filter format

- chain/bitcoind.go
In this commit, we fix a recently introduced bug that would cause
callers that attempted to get a spend notifications for a particular
outpoint to no longer get that precise notification. In a prior commit,
in preparation for the new neutrino gcs filter format, we added a
mapping from script to outpoint that will be used by neutrino, and later
other backends as well. However, we still need to match on outpoint
slices for bitcoind today.
> chain: continue to accept []wire.OutPoint for rescan updates for bitcoind

- waddrmgr/address.go
- waddrmgr/common_test.go
- waddrmgr/manager_test.go
- waddrmgr/scoped_manager.go
- wallet/chainntfns.go
In this PR, we add a new method `DerivationInfo` to the
`ManagedPubKeyAddress` interface. This method is meant to provide callers
with the information necessary to independently derive each key returned
by the various methods provided to derive addresses.
We also update the tests to ensure that when we create addresses, as well as read them from disk, the `DerivationInfo` return values are set properly.
Finally, we fix a bug in the wallet code for disconnecting blocks which would previously ignore an error.
> waddrmgr: add new DerivationInfo method to ManagedPubKeyAddress

- chain/rpc.go
In this commit, we remove the keep-alive logic within the handler of the
RPCClient struct as this logic already exists within the backing
rpclient.Client instance. In this case, we'd completely stop the
connection after the ping timeout (1 min), which would render the
reconnection logic within rpcclient.Client useless.
Fixes https://github.com/lightningnetwork/lnd/issues/1775.
> chain/rpc: remove unnecessary ping keep alive

- wtxmgr/query_test.go
- wtxmgr/tx.go
- wtxmgr/tx_test.go
- wtxmgr/unconfirmed.go
In this PR, we resolve a lingering bug within the wallet where it's possible that an output is added as unconfirmed credit after the fact that it has already confirmed. This would lead to duplicate entries for the same output within the wallet causing double spend transactions to be crafted.
The root cause for the unconfirmed credit being added again is most likely triggered by receiving an unconfirmed `chain.RelevantTx` notification from the backend after the transaction has already confirmed. Ideally this should not happen, but that fix is a lot more involved.
Fixes https://github.com/lightningnetwork/lnd/issues/1494.
> wtxmgr: resolve duplicate entries for outputs within bucketUnspent

- waddrmgr/internal_test.go
- waddrmgr/manager.go
- waddrmgr/manager_test.go
- wallet/wallet.go
This PR moves any address notifications outside of the
db transaction that creates them. This is known to have
resulted in deadlocks, since `chainClient.NotifyReceived`
could block the db transaction from committing.
Doing so also prevents the situation where we send
notifications about the new addresses, but the db txn
fails to commit and the addresses are in fact never
created.
> wallet/wallet: notify addrs+props after db commit

- wallet/chainntfns.go
In this commit, we avoid notifying clients of transactions that we've
received chain.RelevantTx notifications for, but are not found within
the wallet. This can happen as now we'll prevent adding an unconfirmed
transaction to the wallet that already exists as confirmed. Due to this,
UniqueTxDetails will be unable to find the transaction and return nil,
casuing a panic for potential callers.
> wallet/chainntfns: avoid notifying txs if not found within the wallet

- chain/bitcoind_client.go
- chain/bitcoind_conn.go
- wallet/wallet.go
In this PR, we modify the wallet to also set the birthday for its chain client when using a bitcoind backend. We do this to ensure that the client's birthday is set correctly, which will allow it to properly carry its duties.
> chain+wallet: set bitcoind client birthday after wallet init

- .travis.yml
- chain/neutrino.go
- glide.lock
- glide.yaml
- wallet/wallet.go
This PR makes `btcwallet` utilize the changes in https://github.com/lightninglabs/neutrino/pull/96, where we will properly wait for filter headers to be synced before considering the chain backend to be current.
> Wait for neutrino filter headers

- wallet/wallet.go
In this commit, we ensure that when an external private key is imported
into the wallet, that we do not overwrite our existing birthday with the
one provided. If this were to happen and we forced a wallet rescan using
the birthday as our starting point, then we'd miss detecting relevant
on-chain events that occurred between them.
> wallet/wallet: only set new birthday if before current within ImportPrivateKey

- rpc/legacyrpc/methods.go
- wallet/wallet.go
Sometimes it is needed to spend a specific output from the SendOutputs tx. It could be that the tx is still unconfirmed at that point. To do this, the full tx needs to be looked up by using the returned tx hash and the tx outs need to be searched to find the output indices.
This PR adds an output index mapping return value to SendOutputs.
> wallet: return full tx from SendOutputs

- waddrmgr/db.go
- waddrmgr/error.go
- waddrmgr/log.go
- waddrmgr/migrations.go
- waddrmgr/migrations_test.go
- waddrmgr/sync.go
- wallet/chainntfns.go
- wallet/wallet.go
In this PR, we add a new migration to the `waddrmgr` to populate the birthday block for existing wallets. This will deem useful when performing rescans for whatever reason, as we'll now be able to start from this point rather than the genesis block, incurring a longer rescan.
The migration is not reliable since we do not store block timestamps, so we'll need to estimate our height by looking at the genesis timestamp and assuming a block occurs every 10 minutes. This can be unsafe, and cause us to actually miss on-chain events, so a sanity check has also been added to ensure its correctness.
This sanity check performs two main checks: whether the birthday block timestamp reflects a time before the birthday timestamp and whether the delta between these two timestamps is a reasonable amount. …
> wallet+waddrmgr: add migration & sanity check to populate birthday block

- waddrmgr/db.go
- waddrmgr/sync.go
- wallet/chainntfns.go
- wallet/wallet.go
In this commit, we address an issue with the wallet where it would
always request a rescan from the birthday block. This is very crucial
for older wallets, as it'll potentially go through thousands of blocks.
To address this, we'll now only request a rescan from our birthday if
we're recovering our wallet from our seed, the birthday block was rolled
back, or if we're performing our initial sync. Otherwise, we'll request
a rescan from tip.
> wallet/wallet: prevent always rescanning from birthday block

- wallet/chainntfns.go
- wallet/chainntfns_test.go
In this commit, we address an issue that would cause users to be stuck
in an infinite loop by fetching the same candidate birthday block due to
its height not being updated if the sanity check was attempting to fix
an estimate in the future. We fix this by setting the new candidate
height so that new candidate blocks can be fetched and tested.
> wallet/chainntnfs: set height for new birthday block candidate

- cmd/dropwtxmgr/main.go
- waddrmgr/db.go
- waddrmgr/manager.go
- waddrmgr/migrations.go
- waddrmgr/migrations_test.go
- waddrmgr/sync.go
In this commit, we modify the `dropwtxmgr` tool to force a rescan upon
restart from the wallet's birthday block, rather than the chain's
genesis block. We can safely do this as we expect that no on-chain
events relevant to the wallet should happen before this block.  For
older wallets which do not have their birthday block set, the rescan
should start from the genesis block.
> waddrmgr+cmd/dropwtxmgr: start rescan from birthday block

- wallet/wallet.go
In this commit, we modify our initial sync assumption to depend on
whether the wallet's birthday block has been set. We can use this
assumption to prevent costly rescans from the birthday block upon
restarts if there are no UTXOs that exist within the wallet.
> wallet/wallet: redefine initial sync to birthday block not being set

- wallet/wallet.go
This is done to avoid the birthday rescan to fail if the chain backend
reports a bestheight of 0.
Earlier it could happen that we attempted to sync to the birthday, but
since only the genesis block was available, which would be rejected as
birthday block because of the timestamp, it would fail to find a block
and the sync would fail.
> wallet/wallet: assume not current if best height is 0

- waddrmgr/scoped_manager.go
- wallet/createtx.go
- wallet/createtx_test.go
- wallet/mock.go
- wallet/wallet.go
- walletdb/bdb/db.go
- walletdb/interface.go
Useful for creating transactions for fee estimation, e.g.
> wallet: add dryrun arg to tx create, rolling back db if set

- wallet/wallet.go
This fixes an issue reputed by a user that would cause btcwallet to
panic if the full node was stopped while btcwallet was still restoring
the wallet.
> wallet: only log block batch if non-empty

- wallet/wallet.go
In this commit, we rework how `publishTransaction` works in order to correctly handle removing invalid transactions from the wallet's unconfirmed transaction store. This is crucial as otherwise, invalid transactions can remain within the wallet and be used for further transactions, causing a chain of inaccurate transactions.
`publishTransaction` will now only return an error if the transaction fails to be broadcast and it has not been previously seen in the mempool/chain. This is intended in order to provide an easier API to callers. Any other errors when broadcasting the transaction will cause it to be removed from the wallet's unconfirmed transaction store to ensure it maintains an accurate view of the chain.
>  wallet/wallet: remove invalid transactions when broadcast fails

- wallet/wallet.go
In this commit, we fix an issue with the wallet's initial sync logic
where we'd miss processing all of the blocks in the chain. This can
happen if the backend is considered current while we're still catching
up. To address this, we make sure we update our best height to process
those missed blocks.
Co-authored-by: Roei Erez <roeierez@gmail.com>
> wallet: ensure bestHeight is updated before isCurrent check

- chain/neutrino.go
- go.mod
- go.sum
The latest version also includes a change to the way we need to
initialize the rescan object.
> build+chain: update to latest version of neutrino

- wtxmgr/db.go
- wtxmgr/tx_test.go
- wtxmgr/unconfirmed.go
In this commit, we address an issue with the wallet store where it'd be
possible for us to keep lingering unconfirmed transaction entries for an
output that has been spent by a different, confirmed transaction. This
was caused due to us removing all spending transaction entries for a
given output when removing conflicts. Since all of the entries would be
removed, we weren't able to retrieve the hashes of the remaining
spending transactions to remove their records as well. Instead, we
propose to only remove the entry for the specified spending transaction.
> wtxmgr: only remove entry for specified spending transaction

- chain/neutrino.go
In this PR, we address a bug within the wallet when running with Neutrino where it wouldn't be able to mark it as synced with the chain due to not receiving a RescanFinished notification if it was a block behind the chain. This happened because of the order in which the notifications are delivered within the underlying Neutrino ChainService, FilteredBlockConnected gets dispatched before BlockConnected. This doesn't always work however because there is an implicit dependency between them in which BlockConnected must occur first.
To address it, rather than switching the order in which the notifications are dispatched, we just check if we can dispatch the final RescanFinished notification after dispatching BlockConnected.
> chain: dispatch RescanFinished notification after BlockConnected

- wallet/wallet.go
In this commit we fix a lingering bug in our output sanity checks that
would only show up during time periods of persistently higher fees.
Before this commit we would incorrectly use the fee rate instead of the
min relay fee when checking an output for dust. This would cause us to
mistakenly reject a transaction for having a dust output.
We fix this by falling back to using the current min-relayfee.
> wallet: use relay fee to check for dust not fee rate

- wallet/wallet.go
Previously, the wallet would attempt to store the same block it checkpointed during its initial sync when performing a recovery. This would cause the previous block existence validation check to be in place, which would ultimately fail because the previous block was not stored intentionally.
To address this, we always start/resume our recovery from the wallet's best height. This also ensures that we do not rescan the same block again when resuming a recovery after a shutdown.
Fixes https://github.com/lightningnetwork/lnd/issues/3223.
> wallet: start recovery from the wallet's best height

- wallet/wallet.go
In this commit, we speed up creating a fresh wallet when using the btcd
backend. Before this commit, we would need to rescan 10k or so blocks
when creating a new wallet with the btcd backend. btcd will actually
fully scan all the blocks even though we have zero addresses or UTXOs to
look for. As a result, this can take quite some time.
In this commit we modify the starting height of the initial rescan to
start at the birthday height, and only modify it if it's unset, or the
best height of the chain is before this birthday height. As a result, we
won't always have the full 10k block re org safety horizon on disk, but
will tend to this level after we begin to sync forward.
> wallet: speed up bare wallet init when using the btcd backend

- cmd/dropwtxmgr/main.go
- waddrmgr/db.go
- waddrmgr/migrations.go
- waddrmgr/migrations_test.go
- waddrmgr/sync.go
We update the dropwtxmgr utility tool to take into account that the wallet only stores MaxReorgDepth blocks, which introduced an additional constraint when updating the wallet's synced state. The constraint ensures that the previous block exists when updating the wallet's synced state, but this does not hold for the birthday block since it's the first block we'll store.
Fixes #630.
> cmd/dropwtxmgr+waddrmgr: handle constraint when resetting synced state

- wallet/wallet.go
- wtxmgr/tx_test.go
- wtxmgr/unconfirmed.go
We do this as a sanity check for users of the wallet to ensure the wallet maintains a correct representation of the chain.
>  wtxmgr: prevent adding existing confirmed transactions as unconfirmed

- go.mod
- go.sum
- internal/prompt/prompt.go
- snacl/snacl.go
btcsuite/golangcrypto was created to cope with the lack of package management for Go back in the day. This is no longer needed as we now use modules.
Fixes https://github.com/btcsuite/btcwallet/issues/638.
> build: replace use of btcsuite/golangcrypto with golang.org/x/crypto

- go.mod
- go.sum
- walletdb/bdb/db.go
Related to https://github.com/lightningnetwork/lnd/pull/3278
I did see a number of rollbacks occurring on initial startup, but I will need to see if I can recreate this.  Under rollbacks, the freelist must be built again temporarily which is burdensome with large freelists.  Will report back.
Edit: Should be fine to proceed with.
> bdb: specify freelist options by default

- go.mod
- go.sum
- walletdb/go.mod
- walletdb/go.sum
In this commit, we create a new module for `walletdb` in order to allow
external projects to use the project without also having to depend on
the entirety of `btcwallet`. With this commit, projects that depend on
`walletdb` will benefit from a slimmer set of additional dependencies.
> build+walletdb: create new module for walletdb

- btcwallet.go
- cmd/dropwtxmgr/main.go
- waddrmgr/common_test.go
- waddrmgr/manager_test.go
- wallet/createtx_test.go
- wallet/loader.go
- walletdb/bdb/README.md
- walletdb/bdb/db.go
- walletdb/bdb/doc.go
- walletdb/bdb/driver.go
- walletdb/bdb/driver_test.go
- walletsetup.go
This allows external callers to set the option instead. All tests remained with the option enabled.
> multi: extend walletdb bolt driver with NoFreelistSync option

- wtxmgr/tx.go
This change is motivated by https://github.com/lightningnetwork/lnd/issues/3624. We now include the transaction we failed to locate to help track down how the wallet entered its invalid state.
> wtxmgr: improve error message for failed tx record retrieval

- wtxmgr/tx.go
- wtxmgr/tx_test.go
This PR ensures the wallet won't enter an inconsistent state by exiting early in the `addReleventTx` flow in case the transaction is new and it already exists in the wallet.
Without this fix, In the case the existing transaction is already confirmed on-chain the flow updates the `bucketUnminedCredits` but without adding en entry also to the `bucketUnmined` resulting in
inconsistent state.
One example for error due to this state is at this point https://github.com/btcsuite/btcwallet/blob/master/wtxmgr/tx.go#L767
where the next line passes nil to the `readRawTxRecord`. When this flow is executed on startup it causes a panic in lnd.
I verified this fixes the issue in lnd: https://github.com/lightningnetwork/lnd/issues/3640
where the sweeper tries to rebroadcast the same transaction that was …
> Fix broadcast existing transaction

- chain/bitcoind_conn.go
- go.mod
- go.sum
`bitcoind` notifies transactions once they're accepted into the mempool and once they're confirmed in a block. Previously, reading a message from ZMQ would allocate a buffer with the size of the message. This can cause nodes to perform a large number of allocations within a small amount periodically (3000 300B allocations every 10 mins on average), which can cause a lot of GC pressure on lower resourced nodes. To remedy this, we introduce two static buffers, one for blocks and another for transactions, that will be reused for every message read. Each is constrained by its maximum expected size.
> build+chain: reuse buffers when reading ZMQ messages from bitcoind

- go.mod
- go.sum
- goclean.sh
- walletdb/bdb/db.go
- walletdb/bdb/driver_test.go
- walletdb/db_test.go
- walletdb/example_test.go
- walletdb/go.mod
- walletdb/go.sum
- walletdb/interface.go
- walletdb/walletdbtest/interface.go
- wtxmgr/go.mod
- wtxmgr/go.sum
- wtxmgr/tx_test.go
In this PR, we add the trio of sequence based methods that `bbolt` ships with to the main bucket interface. We do this in order to easily allow walletdb as is to be slotted into place where bbolt is currently used, without sacrificing any functionality.
Along the way we fix some issues with sub-modules that resulted in packges not being tested against the latest set of sub-modules. We also resolve an issue with `goclean.sh` that prevented any packages which were themselves sub-modules from being run.
> walletdb: add sequence methods from bbolt to the main bucket interface

- waddrmgr/common_test.go
- waddrmgr/manager.go
This trivial PR exports the fast scrypt options used in unit tests as a public variable so these values can easily be reused in depending projects.
> waddrmgr: export fast scrypt options

- walletdb/bdb/interface_test.go
- walletdb/walletdbtest/interface.go
This PR removes bbolt specific parameters from interface test to
enable testing of other DB drivers trough the same entry point.
> walletdb: generic param passing for walletdb test

- waddrmgr/manager.go
- wallet/wallet.go
It was discovered that the wallet can scan the chain for unnecessary additional addresses that are derived by higher-level applications for custom scripts. This isn't much of an issue for full nodes, but it can cause light clients to scan more than what's required, triggering more false positive matches which lead to block retrieval.
Now, we'll only scan the chain for addresses that belong to each scope's default account, as those are the only one the wallet should be concerned about.
> waddrmgr+wallet: only watch addresses within default key scopes

- waddrmgr/manager.go
- waddrmgr/scoped_manager.go
- wallet/createtx.go
- wallet/wallet.go
Previously, the wallet would determine the key scope to use for change addresses by locating the one compatible with P2WPKH addresses, but this wasn't always safe like in the case when multiple key scopes that supported these addresses existed within the address manager, leading the change address to be created outside of the intended key scope.
Wallets affected by this now need to ensure they scan the chain when performing rescans or recovery attempts for addresses within _all_ existing key scopes, rather than just the default ones, to reflect their proper balance. For newer wallets not affected by this, they should only scan for addresses within their default key scopes.
> wallet: rescan and recover addresses in all relevant key scopes

- chain/neutrino.go
This greatly speeds up wallet recovery with a neutrino backend, as we'll avoid unnecessary round trips for each block filter fetch.
> chain: batch filter fetches for neutrino chain client

- waddrmgr/README.md
- waddrmgr/db.go
- waddrmgr/error.go
- waddrmgr/manager.go
- waddrmgr/manager_test.go
- waddrmgr/scoped_manager.go
- wallet/loader.go
- wallet/wallet.go
- wallet/watchingonly_test.go
This PR allows the creation of managers and accounts that are watch-only.  The state of the database after creation would be identical to the state after calling `Manager.ConvertToWatchingOnly`, assuming accounts with the right xpubs were created in the former case.
Of course, creating a watch-only database is safer, since you don't have to worry about private data ending up in a swap file or the system having been compromised before creation.
> Create watch-only address managers and accounts

- rpc/legacyrpc/methods.go
- rpc/rpcserver/server.go
- wallet/createtx_test.go
- wallet/example_test.go
- wallet/notifications.go
- wallet/wallet.go
- wallet/wallet_test.go
- wtxmgr/db.go
- wtxmgr/query.go
- wtxmgr/tx.go
- wtxmgr/tx_test.go
This change adds optional, user provided labels to transactions. Labels are written to their own bucket, keyed by transaction hash. This approach was taken to avoid the need for migration in the `TxRecord`. 
For the legacy rpc, the existing `Comment` parameter is used. Some fields also have a `CommentTo` field; I'm unsure what this field is for, and it is not present for all send endpoints so I have left it as unimplemented. 
Ready for a first pass of review, however I suspect that my I've generated the protos with the wrong protoc version. `serverchanges.md` does not mention a specific version?
Fixes #693
> wtxmgr: add labels to transactions

- cmd/dropwtxmgr/main.go
- wtxmgr/tx.go
Add an option to drop your tx labels in `dropwtxmgr`. By default, we keep labels to prevent accidental deletion of important tx information that cannot be obtained from chain. This change pulls some of the label read/write logic out into separate logic in `wtxmgr` so we do not have to duplicate it. 
Tested with some labelled txns in lnd - drop wtxmgr, labels remain; drop with `--droplables` and labels are gone.
> dropwtxmgr: add drop labels option

- waddrmgr/manager.go
Not setting this would result in a non-sensible unix timestamp (2288912640) being exposed when the wallet hasn't synced any blocks, like in the case when it's waiting for the backend to sync.
Fixes https://github.com/lightningnetwork/lnd/issues/3270.
> waddrmgr: set timestamp for genesis block sync info

- wallet/wallet.go
The error string was updated in https://github.com/bitcoin/bitcoin/pull/15921/commits/3004d5a12d09d94bfc4dee2a8e8f2291996a4aaf.
> wallet: handle new error string for missing/spent input in bitcoind 0.20

- wallet/wallet.go
Fixes an error where querying the balance while a coin selection is happening accesses the map concurrently:
```
goroutine 250410745 [running]:
runtime.throw(0x12ab8d3, 0x21)
/home/bitcoin/go1.14/src/runtime/panic.go:1112 +0x72 fp=0xc0ac7591f0 sp=0xc0ac7591c0 pc=0x4360b2
runtime.mapaccess2(0x10b1fe0, 0xc00051c8d0, 0xc0ac759304, 0x2c, 0xc02266a4b0)
/home/bitcoin/go1.14/src/runtime/map.go:469 +0x258 fp=0xc0ac759230 sp=0xc0ac7591f0 pc=0x40fe48
github.com/btcsuite/btcwallet/wallet.(*Wallet).LockedOutpoint(...)
/home/bitcoin/go/pkg/mod/github.com/btcsuite/btcwallet@v0.11.1-0.20200219004649-ae9416ad7623/wallet/wallet.go:2780
github.com/btcsuite/btcwallet/wallet.(*Wallet).ListUnspent.func1(0x1591fe0, 0xc0210a8a18, 0xc0210a8a18, 0x0)
/home/bitcoin/go/pkg/mod/github.com/btcsuite/btcwallet@v0.11.1-0 …
```
> wallet: add mutex for locked outpoints

- wallet/txauthor/author.go
In this commit, we fix a 3 year old bug in dust calculation. Before this
commit, the target fee of the transaction to be crafted would be used to
determine dust. If the target fee is very high, then this would cause
over all higher fees, as we'd base that dust computation off of that fee
rate, rather than the min relay fee.
To fix this, we always use the min relay fee at all times when computing
dust.
> wallet/txauthor: fix bug in dust calculation

- go.mod
- go.sum
- wallet/createtx.go
- wallet/createtx_test.go
- wallet/psbt.go
- wallet/psbt_test.go
- wallet/signer.go
- wallet/signer_test.go
- wallet/utxos.go
- wallet/utxos_test.go
Depends on https://github.com/btcsuite/btcutil/pull/178
Adds the methods `FundPsbt` which can perform coin selection and/or fee estimation to fund outputs in a PSBT and `FinalizePsbt` which signs known inputs of a PSBT packet.
We also add `FetchInputInfo` and `ComputeInputScript` which previously resided in `lnd` to make them available to the PSBT signing code and other users of `btcwallet`.
> wallet: add new PSBT funding and finalizing methods

- btcwallet.go
- walletsetup.go
Running with `--usespv` got an error,
```
2020-08-11 20:54:57.642 [INF] BTCW: Version 0.11.0-alpha
2020-08-11 20:54:57.656 [INF] RPCS: Listening on 127.0.0.1:8332
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1692a94]
goroutine 26 [running]:
main.rpcClientConnectLoop(0xc0002b6000, 0xc0000841e0)
/.../btcsuite/btcwallet/btcwallet.go:165 +0x234
created by main.walletMain
/.../btcsuite/btcwallet/btcwallet.go:86 +0x77a
```
Running with `--createtemp` got an error,
```
Creating the wallet...
Unable to create wallet: invalid arguments to bdb.Create -- expected database path and no-freelist-sync option
```
This PR fixes it.
> btcwallet: add missing noFreelistSync in spv mode and temp wallet

- wallet/psbt.go
- wallet/psbt_test.go
To fix a bug where specifying multiple UTXOs that are by themselves
large enough to satisfy the output amount would lead to the rest of them
being added to fees, we need to provide the transaction author with a
constant list of UTXOs. If we didn't, the author would only consider one
input and calculate the change based on that alone. But since we'd add
all inputs to the PSBT, the rest of the amounts would go to fees.
> wallet: use constant input source for change calculation

- wallet/psbt.go
- wallet/psbt_test.go
Because of an incorrect test, it wasn't discovered that the scriptSig
field was being set on the unsigned TX inputs for a nested SegWit input.
This PR fixes the bug and also refactors the test so it would have
caught this specific bug.
> psbt: don't add scriptSig to txIn

- cmd/dropwtxmgr/main.go
- wallet/history.go
We create a more generic copy of the `dropwtxmgr` command's functionality
and export it as the `wallet.DropTransactionHistory` utility function.
It removes all transaction history from the given wallet to force a
full chain rescan. Optionally the user-defined transaction labels can be
preserved.
> Export dropwtxmgr functionality as utility function

- wallet/wallet.go
We would previously request spend notifications for all transaction outputs, leading to irrelevant transactions being found in the wallet's transaction store.
Motivated by https://github.com/lightningnetwork/lnd/issues/3746.
> wallet: only request spend notification for our outputs

- wallet/wallet.go
This commit fixes a panic introduced with #718 that was caused by
looking up addresses in the wrong namespace.
> wallet: fix incorrect namespace name

- btcwallet.go
- cmd/dropwtxmgr/main.go
- config.go
- waddrmgr/common_test.go
- waddrmgr/manager_test.go
- wallet/example_test.go
- wallet/loader.go
- wallet/watchingonly_test.go
- walletdb/bdb/README.md
- walletdb/bdb/db.go
- walletdb/bdb/doc.go
- walletdb/bdb/driver.go
- walletdb/bdb/driver_test.go
- walletdb/bdb/interface_test.go
- walletdb/db_test.go
- walletdb/example_test.go
- walletsetup.go
- wtxmgr/tx_test.go
A new options field, `Timeout`, which is the amount of time the bbolt waits to obtain a file lock, is added.
The option is [specified here](https://pkg.go.dev/github.com/coreos/bbolt?tab=doc#Options).
> bdb: Add timeout options for bbolt

- wtxmgr/db.go
This error would be seen when an old wallet that has yet to update is performing the latest wtxmgr migration. It's possible for the locked outputs bucket to not exist if outputs haven't been locked before, so we should its deletion correctly.
> wtxmgr: ignore ErrBucketNotFound error upon locked outputs bucket deletion

- wallet/wallet.go
- wtxmgr/tx.go
- wtxmgr/tx_test.go
Allows settings arbitrary lock durations. Also adds a `ListLeases` method to get an overview of all current leases. This call is particularly useful to not lose track of leases when longer durations are used.
> wallet: list leases and parameterize duration

- .travis.yml
- Makefile
- cmd/sweepaccount/main.go
- go.mod
- rpc/legacyrpc/methods.go
- rpc/rpcserver/server.go
- waddrmgr/manager.go
- waddrmgr/scoped_manager.go
- wallet/createtx.go
- wallet/createtx_test.go
- wallet/psbt.go
- wallet/psbt_test.go
- wallet/signer.go
- wallet/txauthor/author.go
- wallet/txauthor/author_test.go
- wallet/txsizes/size.go
- wallet/txsizes/size_test.go
- wallet/utxos.go
- wallet/utxos_test.go
- wallet/wallet.go
This PR aims to address the missing gaps for watch-only accounts to actually be used in the context of transaction creation and signing. It also includes some minor changes and surfaces some additional account information that will serve useful for higher level applications and their use of watch-only accounts.
Depends on https://github.com/btcsuite/btcwallet/pull/732.
> waddrmgr+wallet: support transaction creation and signing for watch-only accounts

- chain/bitcoind_conn.go
As reported by https://github.com/lightningnetwork/lnd/issues/5196, the
new atomic integer isn't properly aligned which can caus panics on
32-bit operating systems.. Tof fix this issue, we move the 64-bit
integer to lay after the two 32-bit integers at the top of the struct.
> chain: fix alignment of atomic integers in bitcoind conn struct

- Makefile
- waddrmgr/scoped_manager.go
- wallet/import.go
Simnet was previously left out as it didn't have defined HD versions for some of our key scopes. To allow testing importing accounts into simnet wallets, we fall back to use the mainnet HD versions.
This commit also addresses an issue with simnet wallets that would arise whenever ScopedKeyManager.AccountProperties was invoked:
`failed to retrieve account public key: unsupported net SimNet`
> waddrmgr+wallet: allow account import for simnet wallets

- chain/bitcoind_conn.go
- chain/pruned_block_dispatcher.go
- chain/pruned_block_dispatcher_test.go
It's possible for bitcoind instances to only have connections to pruned nodes after its initial block download, which are incompatible with the PrunedBlockDispatcher. This would result in GetBlock requests for pruned blocks to never resolve. Since bitcoind also exposes a GetNodeAddresses RPC, which returns random reachable addresses from its address manager, we can leverage it to obtain a new candidate set of peers that we otherwise wouldn't obtain through GetPeers.
> chain: implement GetNodeAddresses fallback for PrunedBlockDispatcher

- waddrmgr/manager_test.go
- wallet/loader.go
- wallet/wallet.go
This PR extends the `btcwallet` with new `Create` and `Open` functions that allow users passing an external database. This is useful when using other `walletdb.DB` implementations than `bbolt`.
> wallet: allow using external wallet db

- waddrmgr/scoped_manager.go
- wallet/import.go
- wallet/import_test.go
This method does not commit the database transaction importing the account and returns the first N external and internal addresses, which can be presented to users to confirm whether the account has been imported correctly.
> wallet: add dry run implementation of ImportAccount

- walletdb/bdb/db.go
- walletdb/interface.go
- walletdb/walletdbtest/interface.go
This commit extends the ReadTx (and ReadWriteTx) interface with
ForEachBucket which can be used to iterate through all top level
buckets. This is a missing piece from the walletdb abstraction which
will allow us to iterate all keys in a walletdb opening the possibility
to build generic tools to browse and edit walletdb files regardless of
the underlying driver.
> walletdb: add ForEachBucket to the ReadTx with bbolt implementation

- Makefile
- internal/prompt/prompt.go
- internal/prompt/prompt_js.go
The wallet loader has a dependency to the internal/prompt package for
prompting the user for certain inputs (e.g. wallet password or new
seed).
This makes it impossible for projects that use the wallet as a
dependency and always provide those inputs as parameters to compile for
JavaScript/WebAssembly targets because the prompt code uses some
terminal functionality that is not available in JS syscalls.
By providing a JS specific implementation that just returns an error we
can compile the dependent projects.
Adding acutal support for prompting the user in the browser is currently
not planned as that can easily be circumvented by providing all inputs
as parameters.
cc @Roasbeef @wpaulino
> internal/prompt: allow compilation in js/wasm environment

- wtxmgr/tx.go
- wtxmgr/tx_test.go
Expired leases are kept in the database until the next cleaning round. This commit makes sure that expired leases look like they do not exist to outside callers.
> wtxmgr: filter out expired leases

- wallet/psbt.go
- wallet/psbt_test.go
To support the cpfp fee bump use case where no external outputs are required.
> wallet: allow zero output psbt funding

- wallet/chainntfns.go
- wtxmgr/tx.go
- wtxmgr/tx_test.go
- wtxmgr/unconfirmed.go
Relevant confirmed and unconfirmed transactions may be notified multiple times. The reason seems to be that there are multiple paths that lead to entrance into the `addRelevantTx` function. This will then always trigger a notification regardless if the transaction was already recorded or not.
This PR addresses this issue by adding a new method `InsertTxCheckIfExists` to the `TxStore`, which allows `addRelevantTx` to skip all the logic only required for new transactions, including notification of transactions that were already recorded.
This should fix lightningnetwork/lnd#2267
Arguably adding better testing of this can be added, which I have only done in this PR in a simplistic manner but would improve on.
> Prevent duplicate notifications for (un)confirmed transactions

- go.mod
Fixes #750.
The submodules wallet/txauthor and wallet/txsizes were updated without a
new tag being created. This works fine when compiling btcwallet from
source but fails when using "go get" as that ignores the replace
directives.
@Roasbeef we should push new tags, `wallet/txauthor/v1.0.1` and `wallet/txsizes/v1.0.1` to fix this properly.
> mod: fix submodule versions

- go.mod
- go.sum
- wallet/txauthor/author.go
- wallet/txrules/rules.go
We can now get rid of our incorrect dust calculation which did not give exact values for segwit outputs as it was based on spending a P2PKH output instead.
> mod+wallet: use btcd/mempool IsDust for calculating mempool dust

- waddrmgr/common_test.go
- waddrmgr/manager.go
- waddrmgr/manager_test.go
- wallet/loader.go
- wallet/wallet.go
To make it possible to create or restore a wallet from the extended master root key only, we refactor the loader, wallet and address manager to accept the root key directly instead of the seed.
> wallet: allow wallet to be created from extended master root key directly

- go.mod
- go.sum
- internal/legacy/rename/rename_unix.go
- internal/prompt/prompt.go
- internal/rpchelp/genrpcserverhelp.go
- internal/rpchelp/helpdescs_en_US.go
- internal/rpchelp/methods.go
- signalsigterm.go
By running `go mod tidy -go=1.16`, we also automatically convert the
"legacy" build tag syntax to use the new Go 1.17 compatible variant.
> build: pin mid Go version to 1.16, run new go mod tidy

- chain/pruned_block_dispatcher.go
- chain/pruned_block_dispatcher_test.go
In this commit, we fix the peer selection for the pruned block
dispatcher. Turns out that the bits are actually mutually exclusive: a
node can set the network bit _and_ the limited (pruned bit).
The prior logic would only seek out "pure" nodes, meaning older nodes
that wouldn't set the limited bit when they're a full-full node. We fix
this by ignoring the limited bit, and we'll only look at the network and
segwit bits.
A unit test has also been added to show the issue in the prior filter
function.
> chain: fix peer selection for the pruned block dispatcher

- wallet/psbt.go
- wallet/signer.go
We need to be able to call ScriptForOutput in external code, so we
export it.
cc @yyforyongyu, @Roasbeef
> wallet: export ScriptForOutput

- go.mod
- go.sum
- waddrmgr/address.go
- waddrmgr/db.go
- waddrmgr/manager_test.go
- waddrmgr/scoped_manager.go
Replaces/continues https://github.com/btcsuite/btcwallet/pull/625.
Adds a new witness script address type with witness v0 and v1 support.
We also add a flag `isSecretScript` that can be set to false to make it possible to use a script address in a watch-only wallet.
cc @Roasbeef, @positiveblue
> Add witness script address support

- wallet/wallet.go
Fixed an issue where unconfirmed txn notifications were sometimes missing the appropriate label. The issue was that `addRelevantTx` broadcasts the notification, and then after that `PutTxLabel` updates the label, which leads to a race condition, the result being that notifications for unconfirmed transactions will sometimes not have a label, but if you call `GetTransactions` the label will in fact be there. Calling `PutTxLabel` before `addRelevantTx` fixes the bug.
> Fixed a bug where unconfirmed txn notifications were missing a label

- go.mod
- go.sum
Now that we have a new tagged version of wallet/txauthor, we no longer
need the local replace directive.
> mod: bump wallet/txauthor, remove local replace

- waddrmgr/address.go
- waddrmgr/manager_test.go
This patch makes sure that p2tr addresses are detected as being used
correctly.
> waddrmgr: fix used address detection for p2tr addrs

- .golangci.yml
- Makefile
- btcwallet.go
- chain/neutrino.go
- chain/pruned_block_dispatcher.go
- internal/legacy/keystore/keystore.go
- internal/legacy/keystore/keystore_test.go
- waddrmgr/db.go
- waddrmgr/manager.go
- waddrmgr/scoped_manager.go
- wallet/notifications.go
go get is no longer used to install or build things. Use go install
instead.  Also specify a version so the module's go.mod is not
touched when installing the CI tools.
> CI: fix Makefile not working with go 1.18

- .github/workflows/main.yml
- chain/bitcoind_client.go
- chain/bitcoind_conn.go
- chain/bitcoind_events.go
- chain/bitcoind_events_test.go
- chain/interface.go
This PR reworks and replaces #784. It allows you to poll Bitcoind's RPC interface for new blocks and transactions instead of using the ZMQ interface. 
Thanks to @orbitalturtle for the original PR! 
Closes #784
> chain: RPC polling for block and tx events

- wallet/wallet.go
`(*Wallet).recovery` is the only internal consumer of `(*RecoveryManager).Resurrect`
and `(*Wallet).recoverScopedAddresses`, which together account for all uses
of `(*ScopedKeyManager).DeriveFromKeyPath`. The `(*ScopedKeyManager).mtx` is locked
there, but not the `(*ScopedKeyManager).rootManager.mtx`, which protects
the `cryptoKeyPriv` and `cryptoKeyScript` while being zeroed during `(*Manager).Lock`. There is
some care taken to prevent operations with these keys with the `(*Manager).mtx`
locked, but the actual operations involving the keys are done outside
of the `rootManager.mtx` lock, meaning a `(*Manager).Lock` could occur after
a `(*Manager).IsLocked` check, resulting in a race condition with the keys being zeroed as
they're being read, or even with data being encrypted with a zeroed …
> waddrmgr/wallet: synchronize recovery shutdown with locking

- wallet/wallet.go
In this commit, we have created new struct to store the result of `ListLeasedOutputs`
method. We call `TxDetails` to get value and pkscript of output. Other output
fields are fetched as before.
Fix: #793 
Signed-off-by: Hitanshu Mehta <hitanshu99amehta@gmail.com>
> Add `Value` and `PkScript` in response of `ListLeasedOutputs` method.

- Makefile
- go.mod
- go.sum
- wallet/psbt.go
This bumps the `btcd/btcutil/psbt` library to `v1.1.4` that supports new Taproot fields in PSBTs.
We then add those fields to Taproot inputs, which, in the wallet's case, will only ever be BIP0086 inputs.
cc @Roasbeef, @positiveblue.
> wallet: add Taproot fields to FundPsbt

- waddrmgr/scoped_manager.go
- waddrmgr/tapscript.go
- waddrmgr/tapscript_test.go
- waddrmgr/tlv.go
- waddrmgr/tlv_test.go
- wallet/import.go
Makes it possible to also import a public key as a Taproot output with `ImportPublicKey`. NOTE: This will only ever treat the public key as a BIP-0086 key and derive the Taproot public key accordingly.
All non-BIP-0086 use cases need to use the `ImportTaprootScript` method.
We also add two new use cases where only partial information is available with a `ImportTaprootScript`:
1. Only the internal key and the merkle root key is known (`TaprootKeySpendRootHash`)
2. Only the final Taproot key is known, no information about the tap tweak is available (`TaprootFullKeyOnly`)
> waddrmgr: add Taproot pubkey import, add new tapscript partial info types

- wallet/txauthor/author.go
The CI didn't pick this up before since the main wallet was still using an older version. We'll tag a new txauthor version after this, which'll let us actually update the wallet and eventually lnd.
> wallet/txauthor: fix call to EstimateVirtualSize

- wallet/txsizes/size.go
The input witness estimation for a P2TR was missing the single weight unit for the stack size encoded as a compact int.
This was balanced out by the worst case estimation of the Schnorr signature which can contain the sighash flag, so this wasn't discovered earlier.
@Roasbeef this requires a new tag to be pushed: `wallet/txsizes/v1.2.3`.
cc @benthecarman.
> txsize: add WU for stack size

- go.mod
- go.sum
Version v0.23.2 introduces a [bugfix](https://github.com/btcsuite/btcd/pull/1896) for script witness item sizes. Without this fix, btcwallet fails to handle the testnet block at height 2350076.
> Bump btcd version to v0.23.2

- go.mod
- go.sum
Allows standalone applications that use `btcd` to function properly on mainnet.
> build: update to btcd v0.23.3

- wallet/wallet.go
Debugging a scenario where a lease exists on disk, but the tx associated with that output no longer does. This can potentially happen if a leased output is somehow spent before the lease, or if the lease itself was for an unconfirmed output which was RBF'd (thus the txid changed).
> wallet: log txid:index for leases where tx is unknown

- wallet/wallet.go
The initial version had the arguments swapped. This doesn't show up if both are nil, but can cause some instances to fail that otherwise wouldn't.
> wallet: fix argument order in call to txToOutputs

- wallet/wallet.go
In this commit, we fix a regression that was introduced as a result of the new change scope param. Of cases like spending from an imported account with PSBT, the change scope should be the same as the coin selection scope to ensure that a proper change address is available.
Example failure scenario: imported account uses the p2wkh scope, no other imported accounts, but then we fail when we go to make a change addr as the imported account hasn't had a p2tr account created.
> wallet: ensure change scope is uniform if coin select scope is set

- chain/bitcoind_client.go
- waddrmgr/scoped_manager.go
- wallet/chainntfns.go
Fixes https://github.com/lightningnetwork/lnd/issues/6434.
This PR fixes a bug where we'd detect funds sent to a non-default
scope address when adding a relevant TX for another output (e.g. the
change from sending to the non-default scope address). This would lead
to not recognizing the spend of that output later on and the output
would remain as a "ghost UTXO".
> Fix addresses from non-default scope being detected

- go.mod
- go.sum
- wallet/psbt.go
This relates to lightningnetwork/lnd#7527 and btcsuite/btcd#1964.
This would be my solution where I would fix the problem in lnd, happy to here your thoughts.
Or should we maybe directly check this in the lnd project/package ?
> Verify psbt input data before finalizing

- .gitignore
- chain/chainservice.go
- chain/mocks_test.go
- chain/neutrino.go
- chain/neutrino_test.go
- chain/rescan.go
Fixes #819
Replaces #820
There is datarace in the neutrino client implementation that is causing test
flakes in `lnd`. The shared `rescan` object and the granular
locking strategy allow for the possibility of a segmentation fault when
`NotifyReceived` attempts to call `Update` on a `rescan` that is `nil`.  This
is because the `clientMtx` lock is released after `rescan` is set to `nil`.
The solution here is to be minimally invasive.  Add a new `rescanMtx` mutex
and require that the `NotifyReceived` method and the `Rescan` method
hold the `rescanMtx` lock for the duration of their execution.  Locking and
unlocking of the client is unaffected and changes to the `rescan` object
become atomic.
This PR adds two interfaces `rescanner` and `nutrinoChainService`
to abstract out the dependency on …
> chain: fix NeutrinoClient segfault on NotifyReceived call

- chain/bitcoind_rpc_events.go
- chain/bitcoind_zmq_events.go
- chain/mempool.go
- chain/mempool_test.go
This commit implements a new struct, `cachedInputs`, to provide faster lookup when removing inputs based on a given transaction. Instead of iterating all the inputs to decide whether they should be removed, we now cache `txid -> inputs` so we can update our local mempool faster by iterating much less data.
> chain: optimize removal of inputs in mempool

- wallet/chainntfns.go
- wallet/example_test.go
- wallet/loader.go
- wallet/wallet.go
- wallet/watchingonly_test.go
Replaces #840.
Fixes https://github.com/btcsuite/btcwallet/issues/827.
Main diff vs. #840:
- Don't expose the sync retry interval to the user level config, choose a sane default instead (5 seconds sounds reasonable to me for most cases)
- Make all changes non-breaking to existing API users (add new `OpenWithRetry()` function to wallet, add functional options to loader)
cc  @JoeGruffins, @chappjc, @Roasbeef
> wallet: don't panic, retry instead

- chain/bitcoind_events.go
- chain/interface.go
- chain/mempool.go
- chain/mempool_test.go
- chain/mocks_test.go
- go.mod
- go.sum
Previously when adding a replacement tx to the local mempool, when the txid's nested map becomes empty, we forgot to delete the key from the root map. And when adding the same tx to the `txids` map(which happens in ZMQ), we may treat the tx as a replacement tx. These are now fixed and the related unit tests are added/updated to reflect the fix.
> chain: handle replacement and duplicate txes properly

- chain/mempool.go
- chain/mempool_test.go
- chain/mocks_test.go
Depends on #872, only the last commit is new. We now remove the warning log when querying mempool transactions as it's expected that some of them are not found.
> chain: remove warning log for mempool polling

- chain/mempool.go
Fix a typo found in error string matching.
> chain: fix error match typo

- chain/bitcoind_events.go
- chain/bitcoind_zmq_events.go
- chain/pruned_block_dispatcher.go
- chain/pruned_block_dispatcher_test.go
This change uses the gettxspendingprevout RPC if the bitcoind version is greater or equal to version 24.0.0. In this case, the mempool is no longer used for zmq clients. The original behavior must be kept for rpc polling clients since they notify on new transactions and can only learn about them from polling the bitcoind mempool and keeping track of its own btcwallet mempool.
> chain: detect and use gettxspendingprevout RPC instead of mempool

- chain/bitcoind_client.go
- chain/bitcoind_conn.go
- chain/btcd.go
- chain/interface.go
- chain/neutrino.go
- wallet/rescan.go
There's a race found in `lnd` side re multiple goroutines accessing the `RescanProgress`, [details in this PR.](https://github.com/lightningnetwork/lnd/pull/8094)
It also fixes the case where `bitcoind` is still loading blocks, causing the `NewBitcoindConn` to return an error.
> chain+wallet: fix race over `RescanProgress` message

- chain/mempool.go
Fixes #892.
The return value of bitcoind did not change, bitcoind will return a different error if the `txindex` is not set (e.g. pruned nodes) so we check for the error code now instead of the specific text and include a direct reference of the bitcoind code.
> chain: Match for error code instead of text.

- wallet/wallet.go
- wallet/wallet_test.go
This PR adds a method to the wallet that allows to get transaction data on any transaction given its ID. Useful for (https://github.com/lightningnetwork/lnd/pull/7654).
> wallet: add gettransaction

- chain/bitcoind_events.go
- chain/bitcoind_rpc_events.go
- chain/bitcoind_zmq_events.go
- chain/mempool.go
- chain/mempool_test.go
This PR makes the RPC client to use `gettxspendingprevout` to look up mempool spend for a given output, such that the internal `inputs` can be removed, which can save us quite some memory usage.
> chain: optimize mempool memory usage for RPC clients

- Makefile
Similar to btcsuite/btcd#2107
This pr added a new `help` target for displaying which commonly used commands that the Makefile supported. This is useful when a new developer goes to find a helpful tool for testing or building etc.
> refactor: add `make help` to display the usage for project Makefile

- wallet/createtx.go
- wallet/createtx_test.go
- wallet/psbt.go
- wallet/wallet.go
We want to be able to use the available coin selection strategies outside of just the coin selection methods offered by the wallet. So this PR refactors the code to be re-used.
> wallet: export coin selection strategy code for re-use

- wallet/log.go
- wallet/wallet.go
This commit removes using `spew` on production as the tx log can be extremely large. For instance, when running [this build](https://github.com/lightningnetwork/lnd/actions/runs/7656820228/job/20866038765) the CI crashed because of this [test](https://github.com/lightningnetwork/lnd/pull/8345/commits/11bafe84ff624e0d7a2d56ef00be89567a7d4cbd), that also caused my local terminal to crash, because we are printing a very large invalid tx.
> wallet: downgrade `spew` log to debug and limit its size

- chain/bitcoind_conn.go
- chain/pruned_block_dispatcher.go
- chain/pruned_block_dispatcher_test.go
This addresses  #https://github.com/lightningnetwork/lnd/issues/8250.
(Still need to update the unittests).
So this does not address the related time issue for now which is acutally the case why the requests where failing in the first place.
I would add the new timing logic and introduce the `getblockfrompeer` command for bitcoind >24 (iirc) in a followup PR.
> chain: PrunedBlockDispatcher bugfix.

- wallet/utxos.go
We recently added the ManagedTaprootScriptAddress type which is not a ManagedPubKeyAddress and therefore doesn't store the derivation info. When trying to fetch the input info for such an address we run into the case where we return nil as the error which causes issues further up in the call stack.
This commit fixes the problem by returning an actual error and not the err variable that is nil due to the previous check.
> wallet: return ErrNotMine for script addresses

- chain/bitcoind_client.go
- chain/bitcoind_events_test.go
- chain/bitcoind_zmq_events.go
- chain/btcd.go
- chain/btcd_test.go
- go.mod
- go.sum
This PR adds a new method `LookupInputMempoolSpend` to directly check whether a given input has been spent or not in the mempool.
> chain: add mempool lookup for outpoints

- chain/bitcoind_client.go
- chain/bitcoind_conn.go
- chain/bitcoind_zmq_events.go
- chain/mempool.go
- chain/neutrino.go
- chain/pruned_block_dispatcher.go
- cmd/sweepaccount/main.go
- config.go
- internal/legacy/keystore/keystore.go
- rpc/legacyrpc/methods.go
- waddrmgr/address.go
- waddrmgr/db_test.go
- waddrmgr/error.go
- waddrmgr/manager_test.go
- waddrmgr/migrations.go
- waddrmgr/scoped_manager.go
- waddrmgr/tlv.go
- wallet/createtx.go
- wallet/disksync.go
- wallet/history.go
- wallet/import.go
- wallet/psbt.go
- wallet/utxos.go
- wallet/wallet.go
- walletdb/bdb/driver_test.go
- walletdb/walletdbtest/interface.go
- walletsetup.go
- wtxmgr/error.go
- wtxmgr/tx.go
In this PR we wrap all errors so we can properly use `errors.Is()` to find the cause for any error. This is especially useful for database related problems, so the underlying database error can be unwrapped.
> Wrapp all errors

- chain/mempool.go
It's a bit spammy to have this as debug logs.
> chain: downgrade loggings used in `getRawMempool`

- wallet/createtx.go
- wallet/createtx_test.go
- wallet/psbt.go
- wallet/wallet.go
Related issue: https://github.com/lightningnetwork/lnd/issues/6949#issue-1386947921
and it is needed for https://github.com/lightningnetwork/lnd/pull/8516
This pull request enables `SendOutput` in the wallet to use passed UTXOS as inputs for transactions. All passed UTXOS would be used as inputs.
> Use selected Utxos while crafting txn

- chain/neutrino.go
- go.mod
- go.sum
- wallet/wallet.go
- wallet/wallet_test.go
This PR removes the string matching and makes use of the newly defined errors inside `rpcclient`.
> chain+wallet: make use of the new errors from `rpcclient`

- wallet/createtx.go
- wallet/createtx_test.go
- wallet/wallet.go
Needed for the new design to fix https://github.com/lightningnetwork/lnd/pull/8545
> Add Filter Utxo Filter Function

- waddrmgr/scoped_manager.go
Related to https://github.com/lightningnetwork/lnd/issues/8626.
When deriving a new address, we'll want to store the correct master key fingerprint from the account it's derived from.
This makes sure PSBT signing succeeds even for imported accounts and their change addresses.
> waddrmgr: add MasterKeyFingerprint to new addresses

- rpc/documentation/serverchanges.md
fix a typo: `regenated`->`regenerated`
> chore: fix typos

- chain/bitcoind_client.go
- chain/btcd.go
- chain/errors.go
- chain/errors_test.go
- chain/interface.go
- chain/neutrino.go
- wallet/mock.go
- wallet/wallet.go
Implemented the idea suggested by @Roasbeef [here](https://github.com/btcsuite/btcd/pull/2209#pullrequestreview-2155124809), we now handle the error mapping separately.
I really like this approach, as the chain backend handling is now independent of `btcd`. Image a case where `bitcoind` updates its error str someday, instead of going through the update chain `btcd -> btcwallet -> lnd`, we can now just update via `btcwallet -> lnd`. Think it's also nice to move `rpcclient` to `btcwallet` since it's a chain backend multiplexer, future PR tho.
The original PR when this was added to btcd: https://github.com/btcsuite/btcd/pull/2138
> Add err match in the package `chain`

- go.mod
- go.sum
- wallet/createtx.go
- wallet/import.go
- wallet/psbt.go
- wallet/wallet.go
- wallet/wallet_test.go
Fixes https://github.com/lightningnetwork/lnd/issues/8697.
Because the way the scoped manager uses the OnCommit callback of the
database transaction mechanism, the manager's lock is released first,
then re-acquired in the OnCommit. But during that short time of
releasing the lock, another goroutine might already have updated the
in-memory state.
We add another mutex around the whole database transaction to address
the problem.
> wallet: Avoid duplicate address creation

- wallet/utxos.go
- wallet/utxos_test.go
This PR breaks `FetchInputInfo` into two methods, `FetchOutpointInfo` and `FetchDerivationInfo` so the caller can better control what to fetch from the wallet db.
> wallet: break `FetchInputInfo` into two methods

- wallet/mock.go
- wallet/wallet.go
- wallet/wallet_test.go
The `(*Wallet).recovery` loop is unmonitored, and shutting down the wallet during recovery without locking the wallet first will hang. This change ensures that the recovery loop is ended when `(*Wallet).Stop` is called.
> end recovery on shutdown

- go.mod
- go.sum
This fixes btcwallet on OpenBSD.  Previously, any bbolt methods would error with "function not implemented".
Fixes #949.
> Update bbolt to latest release

- chain/bitcoind_client.go
- chain/errors.go
An error message was renamed in https://github.com/bitcoin/bitcoin/pull/30212.
We should probably start matching on the [`reject-reason`](https://github.com/bitcoin/bitcoin/blob/4c526f575cde43cc49c0236f4d2b15a5fbb6d7ab/src/rpc/mempool.cpp#L146) returned by `testmempoolaccept` RPC instead, as that's less likely to change in the future.
> chain: match on new bitcoind v28.0 errors

- waddrmgr/scoped_manager.go
First of all, the code between the scoped manager and the root manager needs a full rewrite. The lock orders are unmanageable. This PR fixes a potential deadlock (seen on Breez), but it doesn't fix the underlying issue here. The main problem is the locks between scoped manager and the root manager are taken in different orders. Sometimes root manager first, then scoped manager, sometimes the other way around. 
For this PR the decision is to never lock the root manager inside a scoped manager lock. This PR only fixes a single occurence of this issue, there are more occurences elsewhere.
This PR has been in production for a swap server for Breez for a few months now and fixes our deadlock occurrences.
> waddrmgr: fix lock order in importScriptAddress

- chain/btcd.go
Simple fix - looks like we forgot to call `WaitForShutdown` and, add a nil bucket check which was found panic in one of `lnd`'s itests.
> chain: make sure to `WaitForShutdown`

- waddrmgr/manager.go
- waddrmgr/manager_test.go
- waddrmgr/scoped_manager.go
This PR fixes a deadlock caused by methods of `ScopedManager` read-locking the root manager for `WatchOnly()` and `Locked()` calls while the `ScopedManager` itself is locked. This is the reverse order from the normal way of taking locks, but has been hidden by the fact that DB transactions have never happened in parallel until the upcoming postgres changes in LND.
See discussion [here](https://github.com/lightningnetwork/lnd/pull/9242#issuecomment-2495544838) for more details.
The first commit updates a test to cause this failure. The following commits, pushed after CI completes/tests fail, contain the fix.
> waddrmgr: fix deadlock

- .github/workflows/main.yml
As done in https://github.com/lightningnetwork/lnd/pull/9508, we skip this error, an example is this [build](https://github.com/btcsuite/btcwallet/actions/runs/13303231024/job/37162045847).
> .github: ignore Send coverage errors

- .golangci.yml
- cmd/sweepaccount/main.go
- config.go
- internal/legacy/keystore/keystore.go
- netparams/params.go
- sample-btcwallet.conf
closes #955 
Following up on the [comment](https://github.com/btcsuite/btcwallet/issues/955#issuecomment-2356618570), In this PR we add `regtest` support to btcwallet. 
A regtest environment can benefit users who want to test their applications or programs. Specifically, I am working on a project to add [BTCD support in Polar](https://github.com/jamaljsr/polar/issues/302), which depends on this, as all other node implementations operate on regtest. This becomes a blocker as highlighted in this [comment](https://github.com/jamaljsr/polar/pull/1092#issuecomment-2593675239):
> The second blocker is that btcwallet does not support regtest currently, meanwhile all the other node implementations in Polar use regtest. I think this is the real challenge.
- Start BTCD in regtest
```bash
btcd …
```
> feat: add regtest to btcwallet

- wallet/wallet.go
closes #978
~I'm unsure if this is the best solution but it gets me past the block in my issue. It looks to me like this should always hit when restoring with a birthday, but it does not. Does btcwallet not download all headers anyway?~
> waddrmgr: Put client request first in recovery.

- walletdb/bdb/db.go
- walletdb/interface.go
We do not need a write log to read the sequence number in bbolt so we change the interface and make it less strict.
> Move Sequence func to the read interface

- chain/bitcoind_events_test.go
- waddrmgr/common_test.go
- wallet/example_test.go
- wallet/watchingonly_test.go
- walletdb/bdb/driver_test.go
- walletdb/bdb/interface_test.go
- walletdb/db_test.go
- wtxmgr/example_test.go
- wtxmgr/tx_test.go
TempDir returns a temporary directory for the test to use.The directory is automatically removed when the test and
all its subtests complete. More info  https://pkg.go.dev/testing#B.TempDir
Inspired by https://github.com/btcsuite/btcd/pull/2334
📝 Please see our [Contribution Guidelines](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md) for further guidance.
> refactor: use t.TempDir() instead of os.MkdirTemp

- walletdb/bdb/db.go
- walletdb/bdb/driver.go
Allow opening the bbolt database in read-only mode, so we can safe time when opening the db because we do not need to sync the free-list which takes a lot of time.
> walletdb: add readonly mode to bbolt db implementation

- btcwallet.go
- cmd/dropwtxmgr/main.go
- go.mod
- go.sum
- waddrmgr/common_test.go
- waddrmgr/manager_test.go
- wallet/loader.go
- walletsetup.go
Depends on:
https://github.com/btcsuite/btcwallet/pull/998 (needs updated walletdb version)
and
https://github.com/btcsuite/btcwallet/pull/1000 (needs a new wtxmgr tag)
> multi: update walletdb

- .gitignore
- wtxmgr/tx.go
This commit adds a new method `OutputsToWatch`, which returns a list of outpoints the rescan process should be watching for during the startup.
> wtxmgr: add method `OutputsToWatch`

- chain/bitcoind_client.go
- go.mod
- go.sum
- wallet/rescan.go
- wallet/wallet.go
This PR adds a new method `OutputsToWatch` to reload all the relevant outpoints. Previously we used `UnspentOutputs`, which can skip locked outputs and unmined spending txns.
Depends on,
- #1003
> Make sure to reload all outpoints during startup

- waddrmgr/db.go
> waddrmgr: fix error handling to return error on address hash write failure

- chain/bitcoind_zmq_events.go
Add missing spaces on ZMQ connection log.
Currently: 
```
2025-06-03 14:13:38.555 [INF] BTWL: Started listening for bitcoind block notifications via ZMQ on10.99.99.99:28332
2025-06-03 14:13:38.555 [INF] BTWL: Started listening for bitcoind transaction notifications via ZMQ on10.99.99.99:28333
```
> fix(chain): add missing spaces on ZMQ connection logs.

- waddrmgr/manager.go
- wallet/import_test.go
The `NewScopedKeyManager` will skip creating the `imported` account when the watch is watch-only. We now fix it by always creating it even if it's watch-only.
> waddrmgr: make sure to create `imported` account for watchonly

- .golangci.yml
- chain/bitcoind_client.go
- chain/btcd.go
- go.mod
- go.sum
- rpc/legacyrpc/methods.go
- wallet/createtx.go
- wallet/createtx_test.go
- wallet/rescan.go
Replaces https://github.com/btcsuite/btcwallet/pull/959.
Replaces https://github.com/btcsuite/btcwallet/pull/824.
Replaces https://github.com/btcsuite/btcwallet/pull/928.
> Collect small fixes from stale contributor PRs

- chain/bitcoind_client.go
- chain/btcd.go
This reverts commit fc2ac82500abb778caf13847c2e1f170b9621951. Even after adding backend specific workarounds, the changes in above commit still lead to weird errors in the `lnd` CI. So we just revert the changes in the `chain` package (but keep the formatting changes in `wallet`).
> Revert "chain+wallet: skip rescan if address batch is empty"

- .github/workflows/main.yml
- .protolint.yml
- Makefile
- rpc/.clang-format
- rpc/api.proto
- rpc/walletrpc/api.pb.go
> multi: Introduce `protolint` to CI workflow and `make rpc-format` util

- .github/workflows/main.yml
- Makefile
- sample-btcwallet.conf
- scripts/check-sample-btcwallet-conf.sh
> Makefile+workflows+sample-btcwallet.conf: Introduce sample conf check to CI workflow

- Makefile
- btcwallet.go
- build/deployment.go
- build/deployment_dev.go
- build/deployment_prod.go
- build/log.go
- build/log_default.go
- build/log_nolog.go
- build/log_stdlog.go
- build/loglevel_critical.go
- build/loglevel_debug.go
- build/loglevel_default.go
- build/loglevel_error.go
- build/loglevel_info.go
- build/loglevel_off.go
- build/loglevel_trace.go
- build/loglevel_warn.go
- build/version.go
- chain/log.go
- config.go
- log.go
- make/testing_flags.mk
- rpc/legacyrpc/log.go
- waddrmgr/log.go
- wallet/log.go
- wtxmgr/log.go
Towards #1041.
Towards #1015.
Motivated by @yyforyongyu's comment https://github.com/btcsuite/btcwallet/pull/1044#discussion_r2284893434
> make+Makefile: Introduce unit test variants

- wallet/account_manager_benchmark_test.go
- wallet/benchmark_helpers_test.go
In this PR, we benchmark the new `ListAccountsAPI` against a wrapper API around the deprecated `Accounts` to make sure there are no regressions in terms of performance. That deprecation API process happening in upstream PR https://github.com/btcsuite/btcwallet/pull/1050.
Towards https://github.com/btcsuite/btcwallet/issues/1066.
Towards https://github.com/btcsuite/btcwallet/issues/1067.
Towards #1015.
Prev https://github.com/btcsuite/btcwallet/pull/1068.
Next https://github.com/btcsuite/btcwallet/pull/1070.
<div align="center">
<table>
<tr>
<td align="center">
<br>
<sub><b>Allocations per Operation</b></sub>
</td>
<td align="center">
<br>
<sub><b>Execution Time (ns/op)</b></sub>
</td>
<td align="center">
<br>
<sub><b>Memory Usage (B/op)</b></sub>
</td>
</tr>
</table>
</div>
<details …
> [2/8][AccountManager]: benchmark `ListAccounts` API against deprecated `Accounts` wrapper API

- .golangci.yml
- rpc/legacyrpc/methods.go
- rpc/rpcserver/server.go
- waddrmgr/scoped_manager.go
- wallet/account_manager_test.go
- wallet/address_manager.go
- wallet/address_manager_test.go
- wallet/import.go
- wallet/import_test.go
- wallet/interface.go
- wallet/psbt.go
- wallet/signer.go
- wallet/utxos.go
- wallet/wallet.go
- wallet/wallet_test.go
This PR fixes #1032 - the old design has evolved here, detailed below.
The initial design, as captured in `05-address_manager.md`, was a direct and logical grouping of address-related functions. Its key characteristics were:
-   **Low-Level Identifiers**: Methods relied on internal identifiers like `account uint32` and `waddrmgr.KeyScope`. This required the client to have intimate knowledge of the wallet's internal structure, such as BIP derivation schemes.
-   **Flexible but Risky Primitives**: The inclusion of `ListUnusedAddresses` provided flexibility by returning a pool of available addresses. However, it placed the burden of safe address management entirely on the client.
-   **Redundant Parameters**: Some methods required parameters that could be inferred or were constant for a …
>  wallet: add `AddressManager` interface
