btcwallet.go, chain/chain.go, createtx.go, txstore/json.go, txstore/serialization.go, votingpool/pool_test.go, waddrmgr/manager.go, wallet.go
This brings the entire tree closer to but not 100% goclean.sh clean.
=> Address several issues pointed out by lint and vet.

rescan.go, wallet.go
=> Use rescan for initial tx notification registrations.

rpcserver.go, wallet.go
This was previously using the most recently notified (by the chain
package) block, but transaction processing from this block may not be
finished yet.  Using this block's height to calculate the number of
confirmations is therefore incorrect, and can result in every RPC
handler missing transactions or returning transactions from the wrong
block.
=> Use the correct synced block when calculating confs.

config.go, walletsetup.go
The createtemp flag is used to create a temporary simnet wallet for use with btcsim.
The flag only works if the datadir and network to use it on are specified.
After starting btcwallet with the flag, the wallet immediately opens and is functional.
=> Add new --createtemp flag to btcwallet

rpcserver.go
* Better error message when creating account with manager locked
=> Account related enhancements

wallet/chainntfns.go
Seems that this code got lost over time, and the only place where
reorgs were handled were those that happened while wallet was
disconnected.
=> Rollback txstore on disconnected blocks.

chain/chain.go, internal/rpchelp/genrpcserverhelp.go, internal/rpchelp/methods.go, rpchelp_test.go, rpcserver.go, wallet/wallet.go
=> Update btcjson path import paths to new location.

rpcserver.go, wallet/wallet.go
~~This PR based on top of https://github.com/btcsuite/btcwallet/pull/252~~ Merged
The intent is to provide SendPairs as a helper routine to developers to be able to easily send funds from a specified account
=> Sendpairs refactor

internal/zero/array.go, internal/zero/doc.go, internal/zero/slice.go, internal/zero/slice14.go
=> Take advantage of Go 1.5 optimized zeroing.

waddrmgr/error.go, waddrmgr/error_test.go
This is nicer than type asserting and comparing error codes inline.
=> Add waddrmgr.IsError function.

rpcserver.go
=> Correctly handle RPC listen addresses with IPv6 zones.

rpc/legacyrpc/server.go
On invalide credentials return WWW-Authenticate the same way btcd does.
Pointed out by @davec in decred/dcrwallet#14
=> Return WWW-Authenticate header

config.go
=> Change datadir short option to -b.

wallet/createtx.go
Previously, when creating a change address during the process of creating a new transaction an error case would be hit in the `waddrmgr` triggered by attempting to derive a new internal address from under a `waddrmgr.ImportedAddrAccount`. To remedy this error, we now use the default account for change when spending outputs from an imported key. This approach allows funds under the control of imported private keys to be protected under the wallet's seed as soon as they've been partially spent.
=> Allow spending from the waddrmgr.ImportedAddrAccount via wallet.SpendPairs.

wallet/wallet.go
=> Log wallet locks and unlocks.

rpc/legacyrpc/rpcserver_test.go
=> Fix race in TestThrottle test.

rpc/walletrpc/api.pb.go
Fixes build when using newer versions of the grpc packages.
=> Regenerate walletrpc package.

cmd/sweepaccount/main.go, goclean.sh, internal/cfgutil/amount.go
Fix remaining issues discovered by vet.
=> Modify goclean.sh to run go vet recursively.

config.go
=> Ignore config in current directory by default.

rpc/legacyrpc/methods.go
Replace all calls to getrawtransaction with gettxout.
As btcd no longer enables the transaction index by default,
getrawtransaction can no longer be depended on.  gettxout is safe to
use since it queries the utxo set.  This also means that it will
continue to work even when pruning is enabled.
This should be further improved in the future to not look up previous
output scripts over btcd rpc when they are already saved by the
wallet.
Fixes #410.
=> Avoid calling getrawtransaction from signrawtransaction.

rpc/documentation/clientusage.md
=> Fix example node.js client after breaking API change.

README.md
=> Document need for GO15VENDOREXPERIMENT=1.

waddrmgr/common_test.go, waddrmgr/manager_test.go
=> waddrmgr test: fix test race condition

wallet/wallet.go
Migrated from: https://github.com/lightningnetwork/lnd/pull/1501
If we use neutrino as a bitcoin backend - after opening channel we don't count credits for unmined transactions
```
~/g/s/g/l/lnd ❯ lncli connect 03193d512b010997885b232ecd6b300917e5288de8785d6d9f619a8952728c78e8@testnet-lnd.htlc.me 
{
}
~/g/s/g/l/lnd ❯ lncli walletbalance                                                                                                                                                 
{
"total_balance": "163020941",
"confirmed_balance": "163020941",
"unconfirmed_balance": "0"
}
~ ❯ lncli openchannel 03193d512b010997885b232ecd6b300917e5288de8785d6d9f619a8952728c78e8 250000
{
"funding_txid": "fa602ff6cd70a00cf803f581de04b9bb411d0f1bbb2cb0b9ad9b574fdddcdd53"
}
~/g/s/g/l/lnd ❯ lncli walletbalance …
```
=> wallet: fix lost balance of unmined transaction for neutrino

wallet/rescan.go, wallet/wallet.go
This PR resolves an existing issue where an address
generated by btcwallet confirms before the initial rescan
is triggered. Since the rescan would start from the height
that it eventually syncs to, this would cause the wallet to
miss funds that were sent to it.
This is resolved by finding the first block stamp that
surpasses the manager's birthday, and forcing the rescan
to start from that point. Note that the birthday is already
backdated by 2 days when creating the wallet to handle 
inaccurate block header timestamps. When an initial sync
is not being attempted, we will default to using the
manager's last `SyncedTo` block stamp.
=> wallet: start initial rescan from birthday block

wtxmgr/tx_test.go
In this commit, we extend TestRemoveUnminedTx to also account for
checking the store's total balance (confirmed and unconfirmed). It
currently ensures that the UTXO state is correct, but as a sanity check,
we'll also ensure that balances are properly updated.
=> wtxmgr/tx_test: extend TestRemoveUnminedTx to check balances

wallet/wallet.go
In this commit, we fix a regression in the wallet when attempting to
sync new developer test chains such as regtest and simnet. The wallet
would block syncing until a block was mined, but in order to a mine a
block, an address must be generated by the wallet first. This address
generation would block as the syncing logic was already holding the
database's mutex. As a result of this, we'll now accept the genesis
block as the wallet's birthday block, which should allow the wallet to
proceed as intended.
Fixes #594.
Replaces #599.
=> wallet/wallet: accept 0 bestHeight in developer environments

wallet/wallet.go
This is meant to provide a unified interface for publication of transactions, regardless of the active backend.
The error types `ErrDoubleSpend` and `ErrReplacement` also gives some more information to the caller about the type of error, making it easier to take the correct action.
=> Cleanup publication error matching, add ErrDoubleSpend/ErrReplacment

wallet/wallet.go
Normally the wallet doesn't wait for the chain backend to be synced
on regtest/simnet because there we cannot be certain if we are at
the chain tip, as there are no other nodes to compare to. For
Neutrino, this is a bit different because we rely on the cfheader
server to tell us what it thinks the chain tip is. For a wallet
recovery on Neutrino we therefore need to make sure we are at least
synced up to what the server thinks is the tip.
=> wallet: wait for chain sync on Neutrino recovery

.travis.yml, rpc/legacyrpc/methods.go, wallet/createtx.go, wallet/createtx_test.go, wallet/psbt.go, wallet/psbt_test.go, wallet/rand.go, wallet/txsizes/size.go, wallet/wallet.go
This PR adds a new coin selection strategy based on random picks.
=> wallet: add random coin selection

wallet/import.go, wallet/wallet.go
This PR fixes two issues that arose when trying to run a purely watch-only wallet and import accounts from xpubs only:
1. Coin selection requires the wallet to be unlocked. Since there is no unlock in watch-only mode, we need to circumvent that check.
2. When importing default accounts, the scope is well-known in advance and we don't need to take the detour via the address type. So we add a new `ImportAccountWithScope` method that both defines the key scope and address schema to use instead of guessing that information from the address type.
cc @Roasbeef
=> wallet: watch-only account import improvements

wallet/wallet.go
If SendOutputs is called on a watch-only wallet then a transaction is
created but without any signatures. Publishing that transaction will
always fail. But the attempt to publish will already update the internal
state of the wallet so we shouldn't try to publish this unsigned TX.
Instead we return a new error along with the unsigned transaction to
give the caller the chance to sign and publish it through other means.
cc @Roasbeef, @arshbot.
=> wallet: return unsigned TX in watch-only SendOutputs

btcwallet.go, chain/bitcoind_events_test.go, cmd/sweepaccount/main.go, internal/legacy/keystore/keystore.go, rpc/legacyrpc/server.go, rpcserver.go, waddrmgr/common_test.go, wallet/example_test.go, wallet/txsizes/size.go, wallet/watchingonly_test.go, walletdb/bdb/driver_test.go, walletdb/bdb/interface_test.go, walletdb/db_test.go, wtxmgr/tx_test.go
Should be step 1 of https://github.com/lightningnetwork/lnd/issues/6873
=> Fix Taproot input size estimation

go.mod, go.sum
This fixes an error in taproot based fee estimation.
=> build: update to latest versions of txauthor and txsizes

go.mod, go.sum, wallet/createtx.go
Carries the torch from https://github.com/btcsuite/btcwallet/pull/817
=> wallet: add script size for P2TR change output 

wallet/psbt.go, wallet/psbt_test.go
In case we create a change output when funding a PSBT we want to include its derivation path and public key information in the PSBT in order to make the output information more useful and verbose.
This is used in order to create exclusion proofs for our change addresses in Taro when funding any anchor TX through PSBT.
cc @bhandras.
=> wallet: add output info to change output in FundPsbt

wallet/wallet.go
Because the returned error is not always logged by the caller, we want to make sure we log the _cause_ of the failure when transaction broadcasting fails.
In addition we also log the raw transaction as hex in order to allow manual broadcasting in specific cases.
=> wallet: improve logging around transaction broadcast failures

chain/bitcoind_client.go
This PR adds more RPC methods to `BitcoindClient`.
=> chain: add `GetRawMempool` and `GetRawTransaction` to `BitcoindClient`

wallet/wallet.go
Relates to https://github.com/lightningnetwork/lnd/issues/7156.
and https://github.com/lightninglabs/neutrino/pull/278
This PR introduces a new error which handles the case where our backend reports either a `min relay fee not met` error or a `mempool min fee not met`.  I decided to go with a new error because handling this case as a  `ErrDoubleSpend` feels not right because it is not really a doublespend. One could decide whether we want to include the `min relay fee not met` case, but this was a nice way to test it locally, but I find it reasonable to include it too.
With this PR in place we can check for this error in higher level software like `lnd` and behave differently in some situations as menitoned in https://github.com/lightningnetwork/lnd/issues/7156.
=> Handle mempool minimum fee error

wallet/wallet.go
This relates to https://github.com/lightninglabs/neutrino/pull/278 and https://github.com/lightningnetwork/lnd/pull/7746
I will follow @Roasbeef advice reuse the code in the Rebroadcaster Neutrino package. For this we need to refactor the code of the error checking so that we do not depend on the wallet. 
This lead to the introduction of 2 new error types to separate the logging form the error mapping.
=> wallet: refactor broadcast error code.

go.mod, go.sum
To include the error str match fix.
=> mod: update `btcd` version

config.go
I attempted to create a simulation wallet on testnet3, but it failed. I believe the comment is slightly misleading.
=> fix comment

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.md, .github/pull_request_template.md
We now add a pull request template and an issue template.
=> github: add issue and pr templates

.github/pull_request_template.md, .gitignore, docs/README.md, docs/code_formatting_rules.md, docs/contribution_guidelines.md
Add tailored docs for this repo, address this [comment](https://github.com/btcsuite/btcd/pull/2331#discussion_r1980839820).
=> docs: add contribution guidelines

.gemini/styleguide.md
Copied from [lnd](https://github.com/lightningnetwork/lnd/blob/master/.gemini/styleguide.md) repo, localized a bit.
=> .gemini: add `styleguide.md`

.github/workflows/main.yml, Makefile, go.mod
Depends on #1042.
Towards #1041.
Towards #1015.
=> workflows: check go modules tidiness in CI workflow

.github/actions/cleanup-space/action.yml, .github/actions/rebase/action.yml, .github/workflows/main.yml, scripts/check-commit.sh, scripts/check-each-commit.sh
Towards https://github.com/btcsuite/btcwallet/issues/1041.
Towards https://github.com/btcsuite/btcwallet/issues/1015.
Depends on https://github.com/btcsuite/btcwallet/pull/1047.
=> scripts+actions+workflows: add `check-commits` step to CI workflow

chain/errors.go
Included in this version,
- https://github.com/btcsuite/btcwallet/pull/1053
=> Create version `v0.16.17`
